git co 8d500ab .pre-commit-config.yaml
git co 8d500ab requirements.txt
git co 8d500ab setup.py
git co 8d500ab verl/trainer/config/_generated_ppo_megatron_trainer.yaml
git co 8d500ab verl/trainer/config/_generated_ppo_trainer.yaml
git co 8d500ab verl/trainer/config/actor/actor.yaml
git co 8d500ab verl/trainer/config/actor/dp_actor.yaml
git co 8d500ab verl/trainer/config/algorithm.py
git co 8d500ab verl/trainer/config/config.py
git co 8d500ab verl/trainer/config/data/legacy_data.yaml
git co 8d500ab verl/trainer/config/ppo_trainer.yaml
git co 8d500ab verl/trainer/config/ref/ref.yaml
git co 8d500ab verl/trainer/config/reward_model/reward_model.yaml
git co 8d500ab verl/trainer/config/rollout/rollout.yaml
git co 8d500ab verl/trainer/main_ppo.py
git co 8d500ab verl/trainer/ppo/core_algos.py
git co 8d500ab verl/trainer/ppo/metric_utils.py
git co 8d500ab verl/trainer/ppo/ray_trainer.py
git co 8d500ab verl/utils/checkpoint/fsdp_checkpoint_manager.py
git co 8d500ab verl/utils/dataset/rl_dataset.py
git co 8d500ab verl/utils/vllm/utils.py
git co 8d500ab verl/workers/actor/dp_actor.py
git co 8d500ab verl/workers/fsdp_workers.py
git co 8d500ab verl/workers/rollout/vllm_rollout/vllm_rollout_spmd.py
git co 8d500ab verl/workers/sharding_manager/fsdp_vllm.py
git co 8d500ab verl/workers/sharding_manager/megatron_vllm.py
git co 8d500ab verl/trainer/config/ref/dp_ref.yaml